baseURL = "https://stwi.blog/"
publishDir = "docs"
languageCode = "en-us"
theme = "hugo-theme-relearn"

[markup.goldmark.renderer]
    unsafe= true

[params]
themeVariant = ['learn']
disableSearch = true
disableLandingPageButton = true
disableBreadcrumb = false